<a href="https://colab.research.google.com/github/Achal-Hingrajiya/AI_Programming_With_Python_Udacity/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Numpy array

In [2]:
import numpy as np


In [8]:
# 1D array
x = np.array([1, 2, 3, 4])
print("x: ", x)

# Rank of an array = no of dimentions
print("Rank of x: ", x.ndim)
print("Shape of x: ", x.shape)
print()

# 2D array
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("y: ", y)

print("Rank of y: ", y.ndim)
print("Shape of y: ", y.shape)
print("Data type of y: ", y.dtype)

x:  [1 2 3 4]
Rank of x:  1
Shape of x:  (4,)

y:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of y:  2
Shape of y:  (3, 3)
Data type of y:  int64


In [12]:
# 1D array with custom data type
z = np.array([1.3, 2.5, 3.0, 4.1, 5.8], dtype = np.int64)
print(f"Z: {z}\nData type: {z.dtype}\nDimentions: {z.shape}\nRank: {z.ndim}")

Z: [1 2 3 4 5]
Data type: int64
Dimentions: (5,)
Rank: 1


In [14]:
# 2D array with custom data type
p = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(f"P: {p}\nData type: {p.dtype}\nShape: {p.shape}\nRank: {p.ndim}")

P: [[1. 2. 3.]
 [4. 5. 6.]]
Data type: float64
Shape: (2, 3)
Rank: 2


# Saving np array to file

In [15]:
q = np.array([1, 2, 3, 4])
np.save('my_arr', q)

In [17]:
# readig from saved file
r = np.load('my_arr.npy')
print(f"R: {r}\nData type: {r.dtype}\nShape: {r.shape}\nDimensions: {r.ndim}")

R: [1 2 3 4]
Data type: int64
Shape: (4,)
Dimensions: 1
