<a href="https://colab.research.google.com/github/Achal-Hingrajiya/AI_Programming_With_Python_Udacity/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Creating and saving numpy array

## Creating Numpy array

In [ ]:
import numpy as np


In [ ]:
# 1D array
x = np.array([1, 2, 3, 4])
print("x: ", x)

# Rank of an array = no of dimentions
print("Rank of x: ", x.ndim)
print("Shape of x: ", x.shape)
print()

# 2D array
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("y: ", y)

print("Rank of y: ", y.ndim)
print("Shape of y: ", y.shape)
print("Data type of y: ", y.dtype)

x:  [1 2 3 4]
Rank of x:  1
Shape of x:  (4,)

y:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of y:  2
Shape of y:  (3, 3)
Data type of y:  int64


In [ ]:
# 1D array with custom data type
z = np.array([1.3, 2.5, 3.0, 4.1, 5.8], dtype = np.int64)
print(f"Z: {z}\nData type: {z.dtype}\nDimentions: {z.shape}\nRank: {z.ndim}")

Z: [1 2 3 4 5]
Data type: int64
Dimentions: (5,)
Rank: 1


In [ ]:
# 2D array with custom data type
p = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(f"P: {p}\nData type: {p.dtype}\nShape: {p.shape}\nRank: {p.ndim}")

P: [[1. 2. 3.]
 [4. 5. 6.]]
Data type: float64
Shape: (2, 3)
Rank: 2


## Saving np array to file

In [ ]:
q = np.array([1, 2, 3, 4])
np.save('my_arr', q)

In [ ]:
# readig from saved file
r = np.load('my_arr.npy')
print(f"R: {r}\nData type: {r.dtype}\nShape: {r.shape}\nDimensions: {r.ndim}")

R: [1 2 3 4]
Data type: int64
Shape: (4,)
Dimensions: 1


# 2. Using Built-in Functions to Create ndarrays

## Zeros

In [ ]:
# Creating a np arary of zeors
# np.zeros(shape)
z = np.zeros((3,4))
print(f"z:\n{z}\nData type: {z.dtype}\nShape: {z.shape}\nRank: {z.ndim}")

z:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Data type: float64
Shape: (3, 4)
Rank: 2


## Ones

In [ ]:
# Creating a np array of ones
# np.ones(shape)
o = np.ones((4,5))
print(f"o:\n{o}\nData type: {o.dtype}\nShape: {o.shape}\nRank: {o.ndim}")

o:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Data type: float64
Shape: (4, 5)
Rank: 2


## Constants

In [ ]:
# Creating np array of constants
# np.full(shape, n)

c = np.full((4,3), 4)
print(f"c:\n{c}\nData type: {c.dtype}\nDimenstions: {c.shape}\nRank: {c.ndim}")

c:
[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
Data type: int64
Dimenstions: (4, 3)
Rank: 2


In [ ]:
# Creating np array of constants
# np.full(shape, n, dtype)

c = np.full((4,3), 4, np.float64)
print(f"c:\n{c}\nData type: {c.dtype}\nDimenstions: {c.shape}\nRank: {c.ndim}")

c:
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
Data type: float64
Dimenstions: (4, 3)
Rank: 2


## Identity matrix

In [ ]:
# Creating identity matrix 
# np.eye(n)
i = np.eye(4)
print(f"Identity matrix:\n{i}\nData type: {i.dtype}\nShape: {i.shape}\nRank: {i.ndim}")

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Data type: float64
Shape: (4, 4)
Rank: 2


In [ ]:
# Creating identity matrix 
# np.eye(n, dtype)
i = np.eye(4, dtype = np.int64)
print(f"Identity matrix:\n{i}\nData type: {i.dtype}\nShape: {i.shape}\nRank: {i.ndim}")

Identity matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Data type: int64
Shape: (4, 4)
Rank: 2


## Diagonal array

In [ ]:
# Creating diagonal anrrray of constants
dig = np.diag([10, 20, 30])
print(f"Diagonal matrix:\n{dig}\nData type: {dig.dtype}\nShape: {dig.shape}\nRank: {dig.ndim}")

Diagonal matrix:
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
Data type: int64
Shape: (3, 3)
Rank: 2


## Arange

In [ ]:
# Returns evenly spaces values within given interval
# np.arrange(start, stop, step, dtype)
# Simillar to range

x = np.arange(10)
print(f"X: {x}\nData type: {x.dtype}\nShape: {x.shape}\nRank: {x.ndim}")

y = np.arange(5, 10)
print(f"y: {y}\nData type: {y.dtype}\nShape: {y.shape}\nRank: {y.ndim}")

z = np.arange(1, 11, 3)
print(f"z: {z}\nData type: {z.dtype}\nShape: {z.shape}\nRank: {z.ndim}")


X: [0 1 2 3 4 5 6 7 8 9]
Data type: int64
Shape: (10,)
Rank: 1
y: [5 6 7 8 9]
Data type: int64
Shape: (5,)
Rank: 1
z: [ 1  4  7 10]
Data type: int64
Shape: (4,)
Rank: 1


## linspace

In [ ]:
# returns evenly spaced values calculated over the interval [start, stop]
# Even though the np.arange() function allows for non-integer steps, 
# such as 0.3, the output is usually inconsistent, 
# due to the finite floating point precision. 
# np.linspace(start, stop, n, endpoint = Boolean)

x = np.linspace(0,25, 10)
print(f"X: {x}\nData type: {x.dtype}\nShape: {x.shape}\nRank: {x.ndim}")

# Excluding 25
y = np.linspace(0, 25, 10, endpoint = False)
print(f"y: {y}\nData type: {y.dtype}\nShape: {y.shape}\nRank: {y.ndim}")


X: [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
Data type: float64
Shape: (10,)
Rank: 1
y: [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
Data type: float64
Shape: (10,)
Rank: 1


## Reshape fucntions

In [ ]:
# np.reshape(array, newshape, order)
# It gives a new shape to an array without changing its data.

x = np.arange(25)
print(f"X: {x}\nData type: {x.dtype}\nShape: {x.shape}\nRank: {x.ndim}")

x = np.reshape(x, (5,5))
print(f"X: {x}\nData type: {x.dtype}\nShape: {x.shape}\nRank: {x.ndim}")


X: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Data type: int64
Shape: (25,)
Rank: 1
X: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Data type: int64
Shape: (5, 5)
Rank: 2


## Reshape method

In [ ]:
# It returns an array containing the same data with a new shape. 
# np.ndarray.reshape(new_shape)
y = np.arange(20).reshape(4,5)
print(f"y: {y}\nData type: {y.dtype}\nShape: {y.shape}\nRank: {y.ndim}")


y: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Data type: int64
Shape: (4, 5)
Rank: 2


## Random elements

### Random floats

In [ ]:
# Random ndarrays are arrays that contain random numbers.
# np.random.random(shape)
x = np.random.random((3,3))
print(f"X: {x}\nData type: {x.dtype}\nShape: {x.shape}\nRank: {x.ndim}")


X: [[0.06152364 0.63705188 0.02089311]
 [0.89718158 0.9454743  0.82361705]
 [0.98685889 0.9736822  0.7347313 ]]
Data type: float64
Shape: (3, 3)
Rank: 2


### Random integers

In [ ]:
# np.random.randint(start, stop, size=shape)

x = np.random.randint(5, 15, size = (4,3))
print(f"X: {x}\nData type: {x.dtype}\nShape: {x.shape}\nRank: {x.ndim}")


X: [[ 5 13 10]
 [13  9  8]
 [ 5 14 10]
 [ 7  9  9]]
Data type: int64
Shape: (4, 3)
Rank: 2


## Normal distribution

In [ ]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.00937263 -0.02230834 -0.00979539 ... -0.1267282   0.15435128
  -0.04190709]
 [ 0.177417    0.06868852 -0.03654747 ... -0.01652938  0.08803017
  -0.06430392]
 [ 0.04580474 -0.09267967  0.17700331 ...  0.06577097  0.16904917
   0.09169616]
 ...
 [-0.03376396  0.09335165 -0.17448921 ...  0.07018244 -0.02604483
   0.14621741]
 [ 0.07989881 -0.15374616  0.16692514 ... -0.04984877  0.04298297
  -0.0231409 ]
 [ 0.12700792  0.11253919  0.01835494 ... -0.09314883  0.01571929
  -0.00113097]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.00010825011647243708
The maximum value in X is: 0.47397096334357025
The minimum value in X is: -0.5506273834812943
X has 499203 negative numbers
X has 500797 positive numbers


# 3. Accessing, Deleting and Inserting Elements into ndarrays

## Access

### 1D array

In [ ]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


### 2D Array

In [ ]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print X
print()
print('X = \n', X)
print()

# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


## Modify

### 1D Array

In [ ]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print the original x
print()
print('Original:\n x = ', x)
print()

# We change the fourth element in x from 4 to 20
x[3] = 20

# We print x after it was modified 
print('Modified:\n x = ', x)


Original:
 x =  [1 2 3 4 5]

Modified:
 x =  [ 1  2  3 20  5]


### 2D array

In [ ]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print the original x
print()
print('Original:\n X = \n', X)
print()

# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', X)


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Delete

### 1D array

In [ ]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('Original x = ', x)

# delete first and last ele
x = np.delete(x, [0,-1])
print('Modified x = ', x)



Original x =  [1 2 3 4 5]
Modified x =  [2 3 4]


### 2D array

In [ ]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original Y = \n', Y)

# delete first row
# axis = 0 => row
# axis = 1 => column

a = np.delete(Y, 0, axis = 0)
print('\nModified Y = \n', a)

# Delete first and last column
b = np.delete(Y, [0, -1], axis = 1)
print('\nModified Y = \n', b)


Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified Y = 
 [[4 5 6]
 [7 8 9]]

Modified Y = 
 [[2]
 [5]
 [8]]


## Append

### 1D Array

In [ ]:
x = np.arange(5)
print(f"x: {x}\ny: {y}\n")

# appending an element to x
z = np.append(x, 6)
print(f"X after appending 6: {z}")

p = np.append(x, [5,6,7])
# appending list of elements to x
print(f"X after appending [5,6,7]: {p}")



x: [0 1 2 3 4]
y: [5 6 7 8 9]

X after appending 6: [0 1 2 3 4 6]
X after appending [5,6,7]: [0 1 2 3 4 5 6 7]


### 2D Array

In [ ]:
y = np.arange(9).reshape((3,3))
print(f"Y:\n{y}\nshape: {y.shape}\nRank: {y.ndim}")

# Appending a new row
u = np.append(y, [[10, 11, 12]], axis = 0)
print(f"\nY after appending [10, 11, 12]:\n{u}\nshape: {u.shape}\nRank: {u.ndim}")

# Appending a columns
v = np.append(y, [[10], [11], [12]], axis = 1)
print(f"\nY after appending [10], [11], [12]:\n{v}\nshape: {v.shape}\nRank: {v.ndim}")

Y:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape: (3, 3)
Rank: 2

Y after appending [10, 11, 12]:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]]
shape: (4, 3)
Rank: 2

Y after appending [10], [11], [12]:
[[ 0  1  2 10]
 [ 3  4  5 11]
 [ 6  7  8 12]]
shape: (3, 4)
Rank: 2


## Insert

### 1D array

In [4]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print('\nx = ', x)




Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]


### 2D Array

In [3]:

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print Y
print('\nOriginal Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

# We print w
print('\nw = \n', w)

# We print v
print('\nv = \n', v)


Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


## Stacking

### hstack

In [5]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

print('\nx = ', x)
print('\nY = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. 
# We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

print('\nz = \n', z)
print('\nw = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
